# Generated by Django 4.2.7 on 2023-11-23 21:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("galeria", "0002_fotografia_categoria"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fotografia",
            name="foto",
            field=models.ImageField(upload_to=""),
        ),
    ]
