# Generated by Django 4.2.7 on 2023-12-01 17:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("galeria", "0006_fotografia_usuarios"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fotografia",
            old_name="usuarios",
            new_name="usuario",
        ),
    ]
